# Generated by Django 6.0.2 on 2026-03-16 06:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NailArtImageLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='nail_art_library/')),
                ('style_key', models.CharField(max_length=80, unique=True)),
                ('weight_minutes', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='NailDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='nail_designs/')),
                ('tags', models.CharField(help_text='Comma-separated tags (e.g., minimalist, acrylic, gel, floral)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Show in AI recommender?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('message', models.CharField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('category', models.CharField(choices=[('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('extensions', 'Extensions'), ('art', 'Nail Art')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('features', models.JSONField(default=list, help_text='List of service features')),
                ('badge', models.CharField(blank=True, choices=[('popular', 'Popular'), ('premium', 'Premium'), ('trending', 'Trending'), ('classic', 'Classic'), ('', 'None')], default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('login_method', models.CharField(choices=[('email', 'Email Login'), ('google', 'Google OAuth'), ('artist_email', 'Artist Email Login')], max_length=20)),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('artist', 'Artist')], default='client', max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('no_show_warnings', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Awaiting Client', 'Awaiting Client'), ('In Service', 'In Service'), ('Cleaning', 'Cleaning')], default='Available', max_length=20)),
                ('is_active_employee', models.BooleanField(default=True)),
                ('sanitation_until', models.DateTimeField(blank=True, help_text='When sanitation period ends', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Approved', 'Approved'), ('Rescheduling', 'Rescheduling'), ('On-going', 'On-going'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('Waiting', 'Waiting'), ('Approved', 'Approved'), ('Rescheduling', 'Rescheduling'), ('On-going', 'On-going'), ('Finished', 'Finished'), ('Cancelled', 'Cancelled')], help_text='Stores the status before rescheduling was initiated', max_length=20, null=True)),
                ('core_category', models.CharField(blank=True, choices=[('gel_polish', 'Gel Polish'), ('soft_gel_extensions', 'Soft-Gel Extensions')], max_length=20, null=True)),
                ('style_complexity', models.CharField(blank=True, choices=[('plain', 'Plain Gel Polish'), ('minimal', 'Minimal Set'), ('full', 'Full Set'), ('advanced', 'Advanced Set')], max_length=20, null=True)),
                ('tip_length', models.CharField(blank=True, max_length=10)),
                ('tip_shape', models.CharField(blank=True, max_length=20)),
                ('tip_code', models.CharField(blank=True, max_length=10)),
                ('has_custom_reference', models.BooleanField(default=False)),
                ('design_reference_image', models.ImageField(blank=True, null=True, upload_to='bookings/references/')),
                ('builder_checklist', models.JSONField(blank=True, default=dict)),
                ('estimated_work_minutes', models.PositiveIntegerField(default=0)),
                ('cleanup_minutes', models.PositiveIntegerField(default=20)),
                ('estimated_total_minutes', models.PositiveIntegerField(default=20)),
                ('requires_double_slot', models.BooleanField(default=False)),
                ('custom_art_description', models.CharField(blank=True, max_length=500)),
                ('reference_code', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_receipt', models.ImageField(blank=True, null=True, upload_to='payment_receipts/')),
                ('proposed_date', models.DateField(blank=True, null=True)),
                ('proposed_time', models.TimeField(blank=True, null=True)),
                ('reschedule_lock_expires_at', models.DateTimeField(blank=True, null=True)),
                ('actual_start_time', models.DateTimeField(blank=True, help_text='When the session actually started', null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, help_text='When the session actually ended', null=True)),
                ('overtime_duration', models.DurationField(blank=True, help_text='How long the session went over the scheduled time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='booking.artist')),
                ('gallery_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_appointments', to='booking.naildesign')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.service')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='FileUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('payment_receipt', 'Payment Receipt'), ('design_reference', 'Design Reference'), ('other', 'Other')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('is_viewed_by_artist', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_logs', to='booking.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('private_note', models.CharField(blank=True, max_length=500)),
                ('health_safety_flag', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('artist_reply', models.CharField(blank=True, max_length=500)),
                ('artist_replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='booking.appointment')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking.artist')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('old_comment', models.CharField(blank=True, max_length=500)),
                ('old_private_note', models.CharField(blank=True, max_length=500)),
                ('old_health_safety_flag', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='booking.review')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
        migrations.AddField(
            model_name='naildesign',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Base service for this look', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.service'),
        ),
        migrations.CreateModel(
            name='ClientFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('payment_receipt', 'Payment Receipt'), ('design_reference', 'Design Reference'), ('nail_art', 'Nail Art'), ('other', 'Other')], max_length=50)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('is_viewed_by_artist', models.BooleanField(default=False)),
                ('reference_code', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_services', to='booking.service')),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='booking.appointment')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='booking.artist')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_history', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
