# Generated by Django 6.0.2 on 2026-03-17 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='first_name',
            field=models.CharField(blank=True, help_text="Artist's first name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='last_name',
            field=models.CharField(blank=True, help_text="Artist's last name", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional: Link to existing Client user for Django authentication', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.client'),
        ),
    ]
