# Generated by Django 6.0.2 on 2026-03-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_add_artist_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, help_text='Artist login email (unique)', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password for artist login', max_length=128),
        ),
    ]
