# Generated by Django 6.0.2 on 2026-03-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_appointment_core_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='style_complexity',
            field=models.CharField(blank=True, choices=[('plain', 'Plain Gel Polish'), ('minimal', 'Minimal Set'), ('full', 'Full Set'), ('advanced', 'Advanced Set'), ('gel_polish_removal', 'Gel Polish Removal'), ('extensions_removal', 'Extensions Removal')], max_length=20, null=True),
        ),
    ]
