# Generated by Django 6.0.2 on 2026-04-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('gel_polish', 'Gel Polish'), ('extensions', 'Extensions'), ('soft_gel_extensions', 'Soft Gel Extensions'), ('removal', 'Removal')], max_length=20),
        ),
    ]
