# Generated by Django 6.0.2 on 2026-04-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_update_appointment_core_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_start', models.TimeField(blank=True, help_text='Start time for Monday (e.g., 09:00)', null=True)),
                ('monday_end', models.TimeField(blank=True, help_text='End time for Monday (e.g., 18:00)', null=True)),
                ('tuesday_start', models.TimeField(blank=True, help_text='Start time for Tuesday', null=True)),
                ('tuesday_end', models.TimeField(blank=True, help_text='End time for Tuesday', null=True)),
                ('wednesday_start', models.TimeField(blank=True, help_text='Start time for Wednesday', null=True)),
                ('wednesday_end', models.TimeField(blank=True, help_text='End time for Wednesday', null=True)),
                ('thursday_start', models.TimeField(blank=True, help_text='Start time for Thursday', null=True)),
                ('thursday_end', models.TimeField(blank=True, help_text='End time for Thursday', null=True)),
                ('friday_start', models.TimeField(blank=True, help_text='Start time for Friday', null=True)),
                ('friday_end', models.TimeField(blank=True, help_text='End time for Friday', null=True)),
                ('saturday_start', models.TimeField(blank=True, help_text='Start time for Saturday', null=True)),
                ('saturday_end', models.TimeField(blank=True, help_text='End time for Saturday', null=True)),
                ('sunday_start', models.TimeField(blank=True, help_text='Start time for Sunday', null=True)),
                ('sunday_end', models.TimeField(blank=True, help_text='End time for Sunday', null=True)),
                ('slot_duration', models.PositiveIntegerField(default=60, help_text='Duration of each time slot in minutes')),
                ('break_start', models.TimeField(blank=True, help_text='Daily break start time', null=True)),
                ('break_end', models.TimeField(blank=True, help_text='Daily break end time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='booking.artist')),
            ],
            options={
                'verbose_name': 'Artist Availability',
                'verbose_name_plural': 'Artist Availabilities',
            },
        ),
    ]
