# Generated by Django 6.0.2 on 2026-04-09 08:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_add_artist_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='design_reference_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='design_references'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='payment_receipts'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pics'),
        ),
        migrations.AlterField(
            model_name='nailartimagelibrary',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='nail_art_library'),
        ),
        migrations.AlterField(
            model_name='naildesign',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='nail_designs'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='services'),
        ),
    ]
