# Generated by Django 6.0.2 on 2026-04-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_appointment_design_reference_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naildesign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
