# Generated by Django 6.0.2 on 2026-03-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_create_twofactorotp_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='private_note',
        ),
        migrations.RemoveField(
            model_name='revieweditlog',
            name='old_private_note',
        ),
    ]
