# Generated by Django 6.0.2 on 2026-03-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_review_private_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='core_category',
            field=models.CharField(blank=True, choices=[('gel_polish', 'Gel Polish'), ('soft_gel_extensions', 'Soft-Gel Extensions'), ('removal', 'Removal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('manicure', 'Manicure'), ('pedicure', 'Pedicure'), ('extensions', 'Extensions'), ('art', 'Nail Art'), ('removal', 'Removal')], max_length=20),
        ),
    ]
