# Generated by Django 6.0.2 on 2026-03-27 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_appointment_style_complexity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('artist', 'Artist'), ('admin', 'Admin'), ('system', 'System')], default='client', max_length=10)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('booking_created', 'Booking Created'), ('booking_updated', 'Booking Updated'), ('booking_cancelled', 'Booking Cancelled'), ('booking_approved', 'Booking Approved'), ('booking_rescheduled', 'Booking Rescheduled'), ('booking_completed', 'Booking Completed'), ('profile_updated', 'Profile Updated'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('file_uploaded', 'File Uploaded'), ('payment_uploaded', 'Payment Uploaded'), ('artist_status_changed', 'Artist Status Changed'), ('service_created', 'Service Created'), ('service_updated', 'Service Updated'), ('service_deleted', 'Service Deleted'), ('design_created', 'Design Created'), ('design_updated', 'Design Updated'), ('design_deleted', 'Design Deleted'), ('admin_action', 'Admin Action'), ('failed_login', 'Failed Login'), ('otp_generated', 'OTP Generated'), ('otp_verified', 'OTP Verified'), ('two_factor_enabled', 'Two Factor Enabled'), ('two_factor_disabled', 'Two Factor Disabled')], max_length=30)),
                ('description', models.TextField(help_text='Detailed description of the activity')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/user agent information')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity metadata')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='booking.appointment')),
                ('artist', models.ForeignKey(blank=True, help_text='Artist who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='booking.artist')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='booking.service')),
                ('user', models.ForeignKey(blank=True, help_text='Client user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='booking_act_timesta_31de66_idx'), models.Index(fields=['user_type'], name='booking_act_user_ty_4af376_idx'), models.Index(fields=['activity_type'], name='booking_act_activit_2ec312_idx'), models.Index(fields=['user'], name='booking_act_user_id_c56697_idx'), models.Index(fields=['artist'], name='booking_act_artist__626db9_idx')],
            },
        ),
    ]
