# Generated by Django 6.0.2 on 2026-04-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_update_service_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='core_category',
            field=models.CharField(blank=True, choices=[('gel_polish', 'Gel Polish'), ('extensions', 'Extensions'), ('soft_gel_extensions', 'Soft Gel Extensions'), ('removal', 'Removal')], max_length=20, null=True),
        ),
    ]
